config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get '/pages/new', to: 'pages#new', as: 'form'   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStack Developer Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= javascript_importmap_tags %>
<%= render 'shared/navbar' %>

<div class="main-profile d-flex" id="main">
  <div class="intro vh-100">

     <%= image_tag 'chess.jpg', style:"
          height: 35vh;
    border-radius: 30px 300px;
    position: relative;
    left: -47px;
  top: 100px;", class:"mb-1 chesspic" %>

    <%= image_tag 'profile.jpg', style:" height: 40vh;
    border-radius: 219px 99px;
    position: relative;
    left: 20x;
    bottom: 41px;
    box-shadow: 10px 20px blueviolet;", class:"profile" %>
    <div class="first-row">

        <div class="first-column">
                      <h1 class="typewriter">Hi, I'm Beatriz.</h1>

            <h2 class="mb-4"><strong>Fullstack Web Developer <%= link_to('https://github.com/beaafv', target: "_blank") do %>
      <i class="fa-brands fa-github"></i>
    <% end %></b></h2>
          <div class="d-flex buttons">
            <a href="Dutch.pdf" download="Dutch.pdf" class="button1">Download CV</a>
            <%= link_to 'Contact me!', form_path, class:"button12"%>
          </div>
        </div>
</div>

</div>
</div>
<div class="experience d-flex text-center mt-4">
  <div class="row d-flex new" style="flex-direction:column;">
    <h2>I'm FullStack Developer <i class="fa-solid fa-plus" style="color: #ffffff;"></i></h2>
    <p>Le Wagon, batch #1348, Lisbon</p>
    <p> I'm a Fullstack Developer with a background in nursing, combining my compassionate nature and problem-solving skills to create user-centric digital solutions.</p>
    <p>
      <h2>Projects: <p></h2>
      <h2><%= link_to "Fitseek", "https://fitseek.co.uk", target: "_blank", style:" color:white; "  %>  </h2>
      <p>Fitseek is a mobile App created in the last 2 weeks of Le Wagon's bootcamp. The goal was to aggregate workouts in one place.
      </p>
    </p>
    <p> <h2><%= link_to 'Wedding Photography', "https://beaafv.github.io/landingpagefinal", target: "_blank", style:" color:white;" %> </h2></p>
    <p> A landing page build during StepByTech - it was in top 10 choice's of the contest.</p>
    </p>
        <p> <h2><%= link_to 'Chefly', "https://cheflybnb-9551dd5074b5.herokuapp.com/", target: "_blank", style:" color:white;" %> </h2></p>
  <p>Chefly was born during the airbnb week of Le Wagon's Bootcamp. </p>
      <p>Prior experience as a nurse</p>
  </div>
  <%= image_tag 'experience.jpg', style:" border-radius:100px 200px", class:"chessimg1" %>
</div>

<div class="fitseek vh-100" id="fitseek">
 <div class="container box1 justify-content-center vh-100">
    <h2>
      <%= link_to "Fitseek", "https://fitseek.co.uk",
       target: "_blank", style:" color:white; "
       %>
    </h2>
  </div>
</div>
<div class="wedding vh-100">
 <div class="container box1 justify-content-center vh-100">
    <h2>
      <%= link_to 'Wedding Photography', "https://beaafv.github.io/landingpagefinal",
        target: "_blank",
        style:" color:white;"
    %>
    </h2>
  </div>
</div>
<div class="chefly vh-100">
 <div class="container box1 justify-content-center vh-100">
    <h2>
      <%= link_to 'Chefly', "https://cheflybnb-9551dd5074b5.herokuapp.com/",
      target: "_blank", style:" color:black;"
      %>
    </h2>
  </div>
</div>

app/views/pages/new.html.erb
<%= render 'shared/navbar' %>
<div class="container d-flex justify-content-center align-items-center vh-100" id="form">
  <div class="row">
    <form form action="https://getform.io/f/121fffe2-aaa8-47d2-bc83-66252f74fd9d" method="POST" id="form">
       <h2 class="color:white; mb-2"> <i class="fa-solid fa-envelope" style="color: #ffffff;"></i> Contact me! </h2>
           <label for="bride"> Name: </label>
             <input type="text" id="bride" class="name mb-2" name="bride">
             <label for="comments"> Messages </label>
             <textarea name="comments" id="comments" class="message"> </textarea>
            <input type="submit" onclick="functionSubmit()" id="submit" class="submit1 mb-2" value="Submit" name="submit", class="button1">
    </form>
  </div>
</div>

app/views/shared/_navbar.html.erb
    <div class="navbar" data-controller="navbar">
        <div class="navbar-toggle" data-action="click->navbar#toggleMenu">
            <i class="fa-solid fa-bars-staggered fa-xl" id="open" data-target="navbar.openIcon" data-action="hidden->navbar#toggleMenu"></i>
            <i class="fa-sharp fa-regular fa-xmark fa-xl", style="color: #030303; display: none;" id="closed" data-target="navbar.closedIcon" data-action="hidden->navbar#toggleMenu"></i>
        </div>
        <ul class="navbar-menu" id="navbarMenu" data-target="navbar.menu">
          <li><%= link_to 'home', root_path %></li>
           <li><%= link_to 'contact me', form_path %></li>
          <li><a href="#fitseek">Portfolio</a></li>
        </ul>
      </div>